"""Baseline estimation API for FTIR Baseline Workbench."""

from .anchors import (
    AnchorBaselineEstimator,
    AnchorWindow,
    anchor_pchip_baseline,
    multipoint_linear,
    multipoint_linear_baseline,
    pchip,
    pchip_baseline,
    piecewise_linear,
    piecewise_linear_baseline,
    polynomial,
    polynomial_baseline,
)
from .automatic import (
    COARSE_METHODS,
    PYBASELINES_METHODS,
    AutomaticBaselineEstimator,
    PybaselinesUnavailableError,
    airpls,
    arpls,
    asls,
    estimate_coarse,
    linear_detrend,
    linear_detrend_baseline,
    none_baseline,
    offset,
    offset_baseline,
    pspline_arpls,
    pybaselines_baseline,
    rubberband,
    rubberband_baseline,
)
from .collaborative import (
    CollaborativePLSEstimator,
    collab_pls,
    collaborative_pls_baseline,
    estimate_series_baseline,
)
from .composite import (
    CompositeBaselineEstimator,
    compose_baselines,
    composite_baseline,
    estimate_fine,
)
from .endpoint import (
    EndpointWindowEstimator,
    endpoint_window,
    endpoint_window_baseline,
    estimate_endpoint_window,
    estimate_strict_endpoint,
    strict_endpoint,
    strict_endpoint_baseline,
)
from .protocol import BaselineEstimator
from .shared_shape import SharedShapeEstimator, shared_shape, shared_shape_baseline

__all__ = [
    "COARSE_METHODS",
    "PYBASELINES_METHODS",
    "AnchorBaselineEstimator",
    "AnchorWindow",
    "AutomaticBaselineEstimator",
    "BaselineEstimator",
    "CollaborativePLSEstimator",
    "CompositeBaselineEstimator",
    "EndpointWindowEstimator",
    "PybaselinesUnavailableError",
    "SharedShapeEstimator",
    "airpls",
    "anchor_pchip_baseline",
    "arpls",
    "asls",
    "collab_pls",
    "collaborative_pls_baseline",
    "compose_baselines",
    "composite_baseline",
    "endpoint_window",
    "endpoint_window_baseline",
    "estimate_coarse",
    "estimate_endpoint_window",
    "estimate_fine",
    "estimate_series_baseline",
    "estimate_strict_endpoint",
    "linear_detrend",
    "linear_detrend_baseline",
    "multipoint_linear",
    "multipoint_linear_baseline",
    "none_baseline",
    "offset",
    "offset_baseline",
    "pchip",
    "pchip_baseline",
    "piecewise_linear",
    "piecewise_linear_baseline",
    "polynomial",
    "polynomial_baseline",
    "pspline_arpls",
    "pybaselines_baseline",
    "rubberband",
    "rubberband_baseline",
    "shared_shape",
    "shared_shape_baseline",
    "strict_endpoint",
    "strict_endpoint_baseline",
]
