#!/usr/bin/env python3
"""Regenerate synthetic v0.3.0 compatibility bundles from the exact local baseline.

Only generated files are read. Binary fixtures belong in ignored outputs, never
in the public source tree. The worker proves that its imports use the Git archive.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.metadata
import io
import itertools
import json
import os
import subprocess
import sys
import tarfile
import tempfile
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch
from uuid import NAMESPACE_URL, uuid5

import numpy as np

BASE_COMMIT = "9fc13c10ae34bd53cb220d0807edb18c9e2e41dc"


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _table(x: np.ndarray, *ys: np.ndarray, labels: tuple[str, ...]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(["wavenumber", *labels])
    writer.writerows(zip(x, *ys, strict=True))
    return stream.getvalue().encode("utf-8")


def generate(source_root: Path, output: Path, base_commit: str) -> dict:
    import ftir_baseline
    import ftir_workbench
    from ftir_baseline.config import CoarseBaselineConfig, FineBaselineConfig
    from ftir_workbench.batch.export import build_batch_export
    from ftir_workbench.batch.importing import import_sources
    from ftir_workbench.batch.models import BatchWorkspace, PreparationConfig
    from ftir_workbench.batch.service import preview_coarse, preview_fine
    from ftir_workbench.batch.state import (
        confirm_coarse,
        confirm_fine,
        confirm_preparation,
        set_coarse_draft,
        set_fine_draft,
        set_preparation_draft,
        skip_fine,
    )
    from ftir_workbench.batch.workspace import load_batch_workspace, save_batch_workspace

    module_sources = {}
    for module in (ftir_baseline, ftir_workbench):
        module_path = Path(module.__file__).resolve()
        if not module_path.is_relative_to(source_root):
            raise RuntimeError("fixture worker imported code outside the exact Git snapshot")
        module_sources[module.__name__] = module_path.relative_to(source_root).as_posix()
    if ftir_workbench.__version__ != "0.3.0":
        raise RuntimeError("compatibility fixture must be generated by baseline v0.3.0")
    output.mkdir(parents=True, exist_ok=True)
    if any(output.glob("legacy_*.zip")) or (output / "legacy_generation.json").exists():
        raise FileExistsError("choose a fresh output directory; existing fixtures are preserved")

    rng = np.random.default_rng(3100)
    x = np.linspace(1800.0, 900.0, 181)
    a = 0.2 + 0.0001 * x + 0.5 * np.exp(-((x - 1450.0) / 35.0) ** 2)
    a += rng.normal(0.0, 0.001, x.size)
    b = 0.25 + 0.6 * np.exp(-((x - 1230.0) / 50.0) ** 2)
    d = a * 0.75 + 0.02
    other_x = np.linspace(900.0, 1800.0, 91)
    c = 100.0 * 10.0 ** (-0.3 - 0.4 * np.exp(-((other_x - 1600.0) / 50.0) ** 2))
    ws = BatchWorkspace(workspace_id=uuid5(NAMESPACE_URL, "ftir-v031-legacy-workspace").hex)
    counter = itertools.count()

    def stable_uuid():  # type: ignore[no-untyped-def]
        return uuid5(NAMESPACE_URL, f"ftir-v031-legacy-import:{next(counter)}")

    with patch("ftir_workbench.batch.importing.uuid4", stable_uuid):
        wide_ids = import_sources(ws, [("same.csv", _table(x, a, b, d, labels=("A", "B", "D")))])
        other_ids = import_sources(ws, [("same.csv", _table(other_x, c, labels=("C",)))],
                                   input_unit="percent_transmittance")
    if len(wide_ids) != 3 or len(other_ids) != 1 or ws.import_issues:
        raise RuntimeError("synthetic baseline fixture import failed")
    a_id, b_id, d_id = wide_ids
    c_id = other_ids[0]
    set_preparation_draft(ws, a_id, PreparationConfig(
        input_unit="absorbance", wavenumber_range=(1800.0, 900.0),
        baseline_smoothing={"enabled": True, "estimate_only": True},
    ))
    confirm_preparation(ws, a_id)
    for sid, method in ((a_id, "linear"), (b_id, "offset"), (c_id, "none"), (d_id, "linear")):
        set_coarse_draft(ws, sid, CoarseBaselineConfig(method=method))
        preview_coarse(ws, sid)
        confirm_coarse(ws, sid)
    for sid in (a_id, d_id):
        preview_fine(ws, sid)
        confirm_fine(ws, sid)
    skip_fine(ws, b_id)
    set_coarse_draft(ws, d_id, CoarseBaselineConfig(method="offset"))
    preview_coarse(ws, d_id)
    confirm_coarse(ws, d_id)
    set_coarse_draft(ws, a_id, CoarseBaselineConfig(method="none"))
    set_fine_draft(ws, a_id, FineBaselineConfig(endpoint_window_width_cm1=25.0))
    ws.states[a_id].display_preferences = {"zoom": [1600.0, 1200.0]}
    ws.records[a_id] = replace(ws.records[a_id], display_name="Renamed synthetic A")
    ws.display_order = [a_id, b_id, c_id, d_id]
    ws.selected_spectrum_id = b_id

    coarse = build_batch_export(ws, ws.display_order, stage="coarse")
    fine = build_batch_export(ws, ws.display_order, stage="fine", ready_only=True)
    ws.export_history.append({"stage": "fine", "exported": [a_id, b_id]})
    ws.last_export_summary = fine.metadata
    payloads = {
        "legacy_workspace_v030.zip": save_batch_workspace(ws),
        "legacy_coarse_export_v030.zip": coarse.zip_bytes,
        "legacy_fine_export_v030.zip": fine.zip_bytes,
    }
    restored = load_batch_workspace(payloads["legacy_workspace_v030.zip"])
    if restored.display_order != ws.display_order or not restored.states[d_id].fine_stale:
        raise RuntimeError("baseline fixture failed its own roundtrip")
    arrays = {}
    state_evidence = {}
    for sid in ws.display_order:
        record, state = ws.records[sid], ws.states[sid]
        arrays[f"{sid}__raw_x"] = record.wavenumber
        arrays[f"{sid}__raw_y"] = record.raw_intensity
        state_evidence[sid] = {"label": record.original_column_label,
                               "fine_decision": state.fine_decision,
                               "fine_stale": state.fine_stale, "snapshots": {}}
        for stage in ("coarse", "fine"):
            snapshot = getattr(state, stage + "_snapshot")
            if snapshot is None:
                continue
            state_evidence[sid]["snapshots"][stage] = {
                "fingerprint": snapshot.fingerprint,
                "parent_coarse_fingerprint": snapshot.parent_coarse_fingerprint,
                "implementation_fingerprint": snapshot.implementation_fingerprint,
            }
            arrays[f"{sid}__{stage}__x"] = snapshot.result.absorbance_selected.wavenumber
            arrays[f"{sid}__{stage}__estimate"] = snapshot.result.baseline_estimation_spectra
            for name in ("coarse_baseline", "fine_baseline", "total_baseline", "corrected"):
                arrays[f"{sid}__{stage}__{name}"] = getattr(snapshot.result.baseline, name)
    stream = io.BytesIO()
    np.savez(stream, **arrays)
    payloads["expected_arrays.npz"] = stream.getvalue()
    for name, payload in payloads.items():
        (output / name).write_bytes(payload)
    metadata = {
        "generator": "scripts/generate_v031_legacy_fixtures.py",
        "base_commit": base_commit, "source_environment": "exact temporary Git archive",
        "dataset": "fixed seed 3100; analytic Gaussian peaks and synthetic noise only",
        "experimental_data_read": False, "workspace_schema": ws.schema_version,
        "workspace_id": ws.workspace_id, "spectrum_ids": ws.display_order,
        "module_sources": module_sources, "workbench_version": ftir_workbench.__version__,
        "python": sys.version, "dependencies": {name: importlib.metadata.version(name)
                                                for name in ("numpy", "scipy", "pybaselines", "pydantic")},
        "states": state_evidence,
        "artifacts": {name: {"size_bytes": len(payload), "sha256": _sha256(payload)}
                      for name, payload in payloads.items()},
    }
    (output / "legacy_generation.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-commit", default=BASE_COMMIT)
    parser.add_argument("--output", type=Path,
                        default=Path("outputs/validation-private/v031/legacy"))
    parser.add_argument("--source-root", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args()
    output = args.output.resolve()
    if args.source_root is not None:
        metadata = generate(args.source_root.resolve(), output, args.base_commit)
        print(json.dumps(metadata, indent=2, sort_keys=True))
        return 0
    root = Path(__file__).resolve().parents[1]
    resolved = subprocess.check_output(
        ["git", "rev-parse", "--verify", f"{args.base_commit}^{{commit}}"], cwd=root, text=True,
    ).strip()
    payload = subprocess.check_output(["git", "archive", "--format=tar", resolved], cwd=root)
    with tempfile.TemporaryDirectory(prefix="ftir-v031-baseline-") as temporary:
        snapshot = (Path(temporary) / "source").resolve()
        snapshot.mkdir()
        with tarfile.open(fileobj=io.BytesIO(payload), mode="r:") as archive:
            if any(member.issym() or member.islnk()
                   or not (snapshot / member.name).resolve().is_relative_to(snapshot)
                   for member in archive.getmembers()):
                raise RuntimeError("unsafe member in baseline Git archive")
            archive.extractall(snapshot, filter="data")
        environment = dict(os.environ)
        environment["PYTHONPATH"] = str(snapshot / "src")
        completed = subprocess.run(
            [sys.executable, str(Path(__file__).resolve()), "--source-root", str(snapshot),
             "--base-commit", resolved, "--output", str(output)],
            cwd=snapshot, env=environment, check=False,
        )
        return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
